name: CI / CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schedule-gen-web-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest test_app.py
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t leannelu/schedule-gen-web-app .
      - name: Tag image
        run: |
          docker tag leannelu/schedule-gen-web-app:latest schedule-gen-web-app:latest
      - name: Push image
        run: |
          docker push leannelu/schedule-gen-web-app:latest

It looks like you're setting up a CI/CD pipeline with GitHub Actions for a Python-based web application that involves Docker and deployment to a server. However, the deploy job has some issues that need to be addressed. Here's an updated and corrected version of the pipeline:
Key Issues:

    SSH/Password Handling: You cannot use run: ssh and run: password in that manner. You will need to securely authenticate SSH commands, typically via an SSH key, not directly by using passwords.
    Missing Steps: The deploy job has some disorganized steps and lacks structure. The individual run commands should be part of a single step or grouped logically.
    Invalid syntax for runs-on: The deploy job syntax needs to be fixed for the SSH connection and command execution.

Here's an improved version of the YAML configuration:

name: CI / CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schedule-gen-web-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest test_app.py
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t leannelu/schedule-gen-web-app .
      - name: Tag image
        run: |
          docker tag leannelu/schedule-gen-web-app:latest schedule-gen-web-app:latest
      - name: Push image
        run: |
          docker push leannelu/schedule-gen-web-app:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no willi@138.197.107.82 <<EOF
            cd swe-final/5-final-swe_switching_with_econ/schedule-gen-web-app
            pip install -r requirements.txt
            git stash
            git pull
            python3 app.py
          EOF